// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TadkarSample1.DataAccessLayer.Context;

namespace TadkarSample1.DataAccessLayer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210716085513_addingcityandprovince")]
    partial class addingcityandprovince
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TadkarSample1.DataAccessLayer.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Province_Id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Province_Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("TadkarSample1.DataAccessLayer.Entities.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("City_Id")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("Province_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("City_Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("TadkarSample1.DataAccessLayer.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Province");
                });

            modelBuilder.Entity("TadkarSample1.DataAccessLayer.Entities.City", b =>
                {
                    b.HasOne("TadkarSample1.DataAccessLayer.Entities.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("Province_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("TadkarSample1.DataAccessLayer.Entities.Personnel", b =>
                {
                    b.HasOne("TadkarSample1.DataAccessLayer.Entities.City", "City")
                        .WithMany("Personnels")
                        .HasForeignKey("City_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TadkarSample1.DataAccessLayer.Entities.Province", null)
                        .WithMany("Personnels")
                        .HasForeignKey("ProvinceId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("TadkarSample1.DataAccessLayer.Entities.City", b =>
                {
                    b.Navigation("Personnels");
                });

            modelBuilder.Entity("TadkarSample1.DataAccessLayer.Entities.Province", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Personnels");
                });
#pragma warning restore 612, 618
        }
    }
}
